use_exif_size: no
flann_algorithm: KDTREE
feature_process_size: 960
feature_min_frames: 10000
processes: 4
matching_gps_neighbors: 0
matching_gps_distance: 0
matching_graph_rounds: 50
optimize_camera_parameters: yes
reconstruction_algorithm: incremental
undistorted_image_format: tif
bundle_outlier_filtering_type: AUTO
sift_peak_threshold: 0.066
align_orientation_prior: vertical
triangulation_type: ROBUST
retriangulation_ratio: 2
matcher_type: WORDS
feature_type: HAHOG
align_method: orientation_prior
local_bundle_radius: 0